import { GoogleAnalytics, GoogleTagManager } from '@next/third-parties/google'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'

import '@/styles/sass/globals.scss'
import { Footer } from '@/components/molecules'
import { Header } from '@/components/organisms'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Diamond Films',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={montserrat.className}>
        <Header></Header>
        {children}
        <Footer />
      </body>
      <GoogleTagManager
        gtmId="GTM-ND454GP5"
        dataLayerName={`${metadata.title}`}
      />
      <GoogleAnalytics gaId="G-DRBHT7HM35" />
    </html>
  )
}
